language: python

python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly" # currently points to 3.6-dev

sudo: false

notifications:
  email: false
 
# Setup anaconda and install packages
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n dmsky-env python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy healpy pyyaml pytest -c zonca
  - source activate dmsky-env
  - python setup.py install
  
# command to run tests
script: 
  - python -c "import numpy; import scipy; import pylab"
  - python -c "import dmsky"
  - python tests/test_skymap.py
  - python tests/test_density.py
  - python tests/test_jcalc.py