language: python

python:
  - "2.7"
  - "3.4"
#  - "nightly" # currently points to 3.6-dev

sudo: false

notifications:
  email: false
 
# Setup anaconda and install packages
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n dmsky-env python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy healpy pyyaml nose -c conda-forge
  - source activate dmsky-env
  - git clone https://github.com/kadrlica/pymodeler.git
  - cd pymodeler; pip install -r requirements.txt; 
  #- python setup.py install
  - cd -; pip install -r requirements.txt
# command to run tests
script: 
  #- nosetests -v --nocapture
  - export MPLBACKEND=Agg
  - nosetests -v tests/test_skymap.py
  - nosetests -v tests/test_density.py
  - nosetests -v tests/test_jcalc.py